name: country_generator
description: A generator for generating country object from countries json.
version: 1.0.0
homepage: https://github.com/aaassseee/country
repository: https://github.com/aaassseee/country/tree/master/country_generator
issue_tracker: https://github.com/aaassseee/country/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: '>=2.0.0 <3.0.0'
  yaml: '>=3.0.0 <4.0.0'
  path: '>=1.8.0 <2.0.0'
  collection: '>=1.15.0 <2.0.0'
#  country:
#    path:
#      ../country
  country: '>=1.0.0 <2.0.0'

dev_dependencies:
  build_test: ^2.1.5
  flutter_lints: ^1.0.4
  test: ^1.20.1
